name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 1. AUTORISATIONS : Indispensable pour que l'action ait le droit d'écrire sur ton GitHub
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    # 2. CONNEXION : On se connecte au registre GHCR avec un jeton temporaire
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 3. BUILD & PUSH : On remplace la commande manuelle par l'action officielle
    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        # Ton image sera nommée ghcr.io/gosiva/ygege:develop
        tags: ghcr.io/${{ github.repository }}:develop
